#pragma once

// this file is generated by standard_header.py

#if NGS_STANDARD_HEADER_INCLUDE_CASSERT
#	include <cassert>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CCTYPE
#	include <cctype>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CERRNO
#	include <cerrno>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CFENV
#	include <cfenv>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CFLOAT
#	include <cfloat>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CINTTYPES
#	include <cinttypes>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CLIMITS
#	include <climits>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CLOCALE
#	include <clocale>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CMATH
#	include <cmath>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CSETJMP
#	include <csetjmp>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CSIGNAL
#	include <csignal>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CSTDARG
#	include <cstdarg>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CSTDDEF
#	include <cstddef>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CSTDINT
#	include <cstdint>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CSTDIO
#	include <cstdio>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CSTDLIB
#	include <cstdlib>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CSTRING
#	include <cstring>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CTIME
#	include <ctime>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CUCHAR
#	include <cuchar>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CWCHAR
#	include <cwchar>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CWCTYPE
#	include <cwctype>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_ALGORITHM
#	include <algorithm>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_BITSET
#	include <bitset>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_COMPLEX
#	include <complex>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_DEQUE
#	include <deque>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_EXCEPTION
#	include <exception>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_FSTREAM
#	include <fstream>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_FUNCTIONAL
#	include <functional>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_IOMANIP
#	include <iomanip>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_IOSTREAM
#	include <iostream>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_IOS
#	include <ios>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_IOSFWD
#	include <iosfwd>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_IOSTREAM
#	include <iostream>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_ISTREAM
#	include <istream>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_ITERATOR
#	include <iterator>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_LIMITS
#	include <limits>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_LIST
#	include <list>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_LOCALE
#	include <locale>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_MAP
#	include <map>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_MEMORY
#	include <memory>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_NEW
#	include <new>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_NUMERIC
#	include <numeric>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_OSTREAM
#	include <ostream>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_QUEUE
#	include <queue>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_SET
#	include <set>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_SSTREAM
#	include <sstream>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_STACK
#	include <stack>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_STDEXCEPT
#	include <stdexcept>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_STREAMBUF
#	include <streambuf>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_STRING
#	include <string>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_TYPEINFO
#	include <typeinfo>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_UTILITY
#	include <utility>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_VALARRAY
#	include <valarray>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_VECTOR
#	include <vector>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_ARRAY
#	include <array>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_ATOMIC
#	include <atomic>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CHRONO
#	include <chrono>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CODECVT
#	include <codecvt>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CONDITION_VARIABLE
#	include <condition_variable>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_FORWARD_LIST
#	include <forward_list>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_FUTURE
#	include <future>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_INITIALIZER_LIST
#	include <initializer_list>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_MUTEX
#	include <mutex>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_RANDOM
#	include <random>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_RATIO
#	include <ratio>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_REGEX
#	include <regex>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_SCOPED_ALLOCATOR
#	include <scoped_allocator>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_SYSTEM_ERROR
#	include <system_error>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_THREAD
#	include <thread>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_TUPLE
#	include <tuple>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_TYPE_TRAITS
#	include <type_traits>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_TYPEINDEX
#	include <typeindex>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_UNORDERED_MAP
#	include <unordered_map>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_UNORDERED_SET
#	include <unordered_set>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_SHARED_MUTEX
#	include <shared_mutex>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_ANY
#	include <any>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CHARCONV
#	include <charconv>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_EXECUTION
#	include <execution>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_FILESYSTEM
#	include <filesystem>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_MEMORY_RESOURCE
#	include <memory_resource>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_OPTIONAL
#	include <optional>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_STRING_VIEW
#	include <string_view>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_VARIANT
#	include <variant>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_BARRIER
#	include <barrier>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_BIT
#	include <bit>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_COMPARE
#	include <compare>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_CONCEPTS
#	include <concepts>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_COROUTINE
#	include <coroutine>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_FORMAT
#	include <format>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_LATCH
#	include <latch>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_NUMBERS
#	include <numbers>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_RANGES
#	include <ranges>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_SEMAPHORE
#	include <semaphore>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_SOURCE_LOCATION
#	include <source_location>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_SPAN
#	include <span>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_STOP_TOKEN
#	include <stop_token>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_SYNCSTREAM
#	include <syncstream>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_VERSION
#	include <version>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_EXPECTED
#	include <expected>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_FLAT_MAP
#	include <flat_map>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_FLAT_SET
#	include <flat_set>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_GENERATOR
#	include <generator>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_MDSPAN
#	include <mdspan>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_PRINT
#	include <print>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_SPANSTREAM
#	include <spanstream>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_STACKTRACE
#	include <stacktrace>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_STDFLOAT
#	include <stdfloat>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_DEBUGGING
#	include <debugging>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_HAZARD_POINTER
#	include <hazard_pointer>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_INPLACE_VECTOR
#	include <inplace_vector>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_LINALG
#	include <linalg>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_RCU
#	include <rcu>
#endif

#if NGS_STANDARD_HEADER_INCLUDE_TEXT_ENCODING
#	include <text_encoding>
#endif

